# https://github.com/yarnpkg/berry/pull/5544#issuecomment-1613661101
injectEnvironmentFiles: []

nodeLinker: node-modules
nmMode: hardlinks-local
compressionLevel: 0
enableGlobalCache: false
supportedArchitectures:
  cpu:
    - current
  libc:
    - current
  os:
    - current
yarnPath: .yarn/releases/yarn-4.0.0-rc.47.cjs
lockfileFilename: ./yarn.no-compress.lock
installStatePath: .yarn/install-state.no-compress.gz
cacheFolder: .yarn/benchmark-cache/no-compress
