# https://github.com/yarnpkg/berry/pull/5544#issuecomment-1613661101
injectEnvironmentFiles: []

nodeLinker: pnp
nmMode: hardlinks-local
compressionLevel: 0
lockfileFilename: ./yarn.pnp.no-compress.lock
installStatePath: .yarn/install-state.pnpm.no-compress.gz
enableGlobalCache: false
cacheFolder: .yarn/benchmark-cache/pnp-no-compress
supportedArchitectures:
  cpu:
    - current
  libc:
    - current
  os:
    - current
yarnPath: .yarn/releases/yarn-4.0.0-rc.47.cjs