name: 'Build benchmarks'
on: [push]
jobs:
  bench:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    env:
      YARN_LOCKFILE_FILENAME: 'yarn.no-compress.lock'
      YARN_COMPRESSION_LEVEL: '0'
      PRISMA_SKIP_POSTINSTALL_GENERATE: 'false'
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 'true'

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📥 YARN Monorepo install
        uses: ./.github/actions/yarn-nm-install

      - name: YARN Nextjs build
        working-directory: ${{ github.workspace }}/apps/nextjs-app
        run: yarn build

      - name: YARN Debug size
        working-directory: ${{ github.workspace }}/apps/nextjs-app
        run: yarn check-size

      - name: 🧹 Reset install and builds
        run: npx -y rimraf@5.0.1 --glob "**/node_modules" "**/.next" "**/.cache"

      - name: 📥 PNPM Monorepo install
        uses: ./.github/actions/pnpm-install

      - name: PNPM Nextjs build
        working-directory: ${{ github.workspace }}/apps/nextjs-app
        run: pnpm build

      - name: PNPM Debug size
        working-directory: ${{ github.workspace }}/apps/nextjs-app
        run: pnpm run check-size

