# Bench yarn with compression vs without + action/cache
name: 'Install benchmarks'
on: [push]
jobs:
  bench:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: ♻ Setup yarn cache (no-compress)
        uses: actions/cache@v3
        id: yarn-benchmark-cache-no-compress
        with:
          path: ./.yarn/benchmark-cache/no-compress
          key: yarn-benchmark-cache-no-compress-${{ hashFiles('yarn.no-compress.lock') }}
          restore-keys: |
            yarn-benchmark-cache-no-compress

      #- name: ♻ Setup yarn pnp cache (no-compress)
      #  uses: actions/cache@v3
      #  id: yarn-pnp-benchmark-cache-no-compress
      #  with:
      #    path: ./.yarn/benchmark-pnp-cache/no-compress
      #    key: yarn-pnp-benchmark-cache-no-compress-${{ hashFiles('yarn.pnp.lock', '.pnp*') }}
      #    restore-keys: |
      #      yarn-pnp-benchmark-cache-no-compress

      - name: ♻ Setup yarn cache (mixed-compress)
        uses: actions/cache@v3
        id: yarn-benchmark-cache-mixed-compress
        with:
          path: ./.yarn/benchmark-cache/mixed-compress
          key: yarn-benchmark-cache-mixed-compress-${{ hashFiles('yarn.mixed-compress.lock') }}
          restore-keys: |
            yarn-benchmark-cache-mixed-compress

      # PNPM does not rotate the cache (store) like Yarn. When the lock change new packages will
      # be added, older won't be removed and so the action/cache storage will grow over time.
      # The cache-rotation.YEAR_MONTH allows to invalidate after a period.
      - name: ⚙ Cache rotation keys for pnpm (yarn does not need it as it rotates the cache)
        id: cache-rotation
        run: echo "YEAR_MONTH=$(/bin/date -u "+%Y%m")" >> $GITHUB_OUTPUT

      - name: ⚙ Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.5.1

      - name: ⚙ Expose pnpm config(s) through "$GITHUB_OUTPUT"
        id: pnpm-config
        run: echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      # PNPM store seems OS / Architecture dependent while Yarn cache isn't. If the action runs on Win/Mac/Linux
      # you'll have 3 caches
      - name: ♻ Setup pnpm cache
        uses: actions/cache@v3
        id: pnpm-benchmark-store-cache
        with:
          path: ${{ steps.pnpm-config.outputs.PNPM_STORE_PATH }}
          key: ${{ runner.os }}-pnpm-benchmark-store-cache-${{ steps.cache-rotation.outputs.YEAR_MONTH }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-benchmark-store-cache-${{ steps.cache-rotation.outputs.YEAR_MONTH }}-

      - name: 📥 Yarn install dependencies  (mixed-compress)
        run: yarn install --immutable --inline-builds
        env:
          YARN_ENABLE_GLOBAL_CACHE: 'false' # Prune cache (yarn.lock changes)
          YARN_NM_MODE: 'hardlinks-local'
          YARN_GLOBAL_FOLDER: '.yarn/global-mixed-compress/'
          YARN_CACHE_FOLDER: '.yarn/benchmark-cache/mixed-compress'
          YARN_COMPRESSION_LEVEL: 'mixed'
          YARN_LOCKFILE_FILENAME: 'yarn.mixed-compress.lock'
          YARN_INSTALL_STATE_PATH: .yarn/install-state-mixed-compress.gz
          HUSKY: '0'
          PRISMA_SKIP_POSTINSTALL_GENERATE: 'true'
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 'true'

      - name: 🧹 Remove node_modules
        run: npx -y rimraf@latest --glob "**/node_modules"

      - name: 📥 Yarn install dependencies (no-compress)
        run: yarn install --immutable --inline-builds
        env:
          YARN_ENABLE_GLOBAL_CACHE: 'false' # Prune cache (yarn.lock changes)
          YARN_NM_MODE: 'hardlinks-local'
          YARN_GLOBAL_FOLDER: '.yarn/global-no-compress/'
          YARN_CACHE_FOLDER: '.yarn/benchmark-cache/no-compress'
          YARN_LOCKFILE_FILENAME: 'yarn.no-compress.lock'
          YARN_COMPRESSION_LEVEL: '0'
          YARN_INSTALL_STATE_PATH: .yarn/install-state-no-compress.gz
          HUSKY: '0'
          PRISMA_SKIP_POSTINSTALL_GENERATE: 'true'
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 'true'

      #- name: 🧹 Remove node_modules
      #  run: npx -y rimraf@latest --glob "**/node_modules"
      #- name: 📥 Yarn PNP install
      #  run: yarn install --immutable --inline-builds
      #  env:
      #    YARN_ENABLE_GLOBAL_CACHE: 'false' # Prune cache (yarn.lock changes)
      #    YARN_NODE_LINKER: 'pnp'
      #    YARN_GLOBAL_FOLDER: '.yarn/global-no-cache/'
      #    YARN_CACHE_FOLDER: '.yarn/benchmark-pnp-cache/no-compress'
      #    YARN_LOCKFILE_FILENAME: 'yarn.pnp.lock'
      #    YARN_COMPRESSION_LEVEL: '0'
      #    HUSKY: '0'
      #    PRISMA_SKIP_POSTINSTALL_GENERATE: 'true'

      - name: 🧹 Remove node_modules
        run: npx -y rimraf@latest --glob "**/node_modules"

      - name: 📥 Yarn install no-cache (mixed-compress)
        run: yarn install --immutable --inline-builds
        env:
          YARN_ENABLE_GLOBAL_CACHE: 'false' # Prune cache (yarn.lock changes)
          YARN_NM_MODE: 'hardlinks-local'
          YARN_GLOBAL_FOLDER: '.yarn/global-no-cache/'
          YARN_CACHE_FOLDER: '.yarn/benchmark-cache/no-cache'
          YARN_LOCKFILE_FILENAME: 'yarn.mixed-compress.lock'
          YARN_COMPRESSION_LEVEL: 'mixed'
          YARN_INSTALL_STATE_PATH: .yarn/install-state-no-cache.gz
          HUSKY: '0'
          PRISMA_SKIP_POSTINSTALL_GENERATE: 'true'
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 'true'

      - name: 🧹 Remove node_modules
        run: npx -y rimraf@latest --glob "**/node_modules"

      - name: 📥 Yarn install no-cache (no-compress)
        run: yarn install --immutable --inline-builds
        env:
          YARN_ENABLE_GLOBAL_CACHE: 'false' # Prune cache (yarn.lock changes)
          YARN_NM_MODE: 'hardlinks-local'
          YARN_GLOBAL_FOLDER: '.yarn/global-no-cache-no-comp/'
          YARN_CACHE_FOLDER: '.yarn/benchmark-cache/no-cache-no-comp'
          YARN_LOCKFILE_FILENAME: 'yarn.no-compress.lock'
          YARN_COMPRESSION_LEVEL: '0'
          YARN_INSTALL_STATE_PATH: .yarn/install-state-no-cache-no-compress.gz
          HUSKY: '0'
          PRISMA_SKIP_POSTINSTALL_GENERATE: 'true'
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 'true'

      - name: 🧹 Remove node_modules
        run: npx -y rimraf@latest --glob "**/node_modules"

      - name: 📥 PNPM install
        shell: bash
        run: pnpm install --frozen-lockfile --prefer-offline
        env:
          HUSKY: '0'
          PRISMA_SKIP_POSTINSTALL_GENERATE: 'true'
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 'true'

      - name: 🧹 Remove node_modules
        run: npx -y rimraf@latest --glob "**/node_modules"

      - name: 📥 PNPM install no-cache
        shell: bash
        run: pnpm install --store-dir ./node_modules/.pnpm-global-store --frozen-lockfile --prefer-offline
        env:
          HUSKY: '0'
          PRISMA_SKIP_POSTINSTALL_GENERATE: 'true'
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 'true'

